feat: add paseto extension
hertz-contrib/paseto pull request #1
Opened 2023-03-22 00:32 UTC by Claude-Zq

#### What type of PR is this?
feat

#### What this PR does / why we need it (en: English/zh: Chinese):

en: add paseto middleware
zh: 添加 `paseto` 中间件

#### Which issue(s) this PR fixes:
Fixes https://github.com/cloudwego/hertz/issues/618

2023-03-22 03:23 UTC, li-jin-gou commented
PATL @zstone12 @L2ncE

2023-03-22 03:24 UTC, li-jin-gou commented
Also I'm curious if there are any practical use scenarios? verify that your middleware is usable in complex scenarios.

2023-03-22 03:37 UTC, Claude-Zq commented
> Also I'm curious if there are any practical use scenarios? verify that your middleware is usable in complex scenarios.

soon will be used in [FreeCar](https://github.com/CyanAsterisk/FreeCar)

2023-03-22 03:58 UTC, L2ncE requested changes

2023-03-22 03:58 UTC, L2ncE commented on generator.go
> +		if tk, err := newTokenFromClaims(stdClaims, customClaims, footer); err != nil {
using `utils.H` instead of `map[string]interface{}`

2023-03-22 03:58 UTC, L2ncE commented on go.mod
> +	github.com/cloudwego/hertz v0.5.2
update hertz version

2023-03-22 03:58 UTC, L2ncE commented on parser.go
> +func NewV4PublicParseFunc(asymmetricPubKey string, implicit []byte, options ...ParseOption) (ParseFunc, error) {
Add comments to all public functions

2023-03-22 03:58 UTC, L2ncE commented on README.md
> +
Can you introduce the difference of each version of paseto through a table

2023-03-22 04:02 UTC, L2ncE commented on paseto_test.go
> +	assert.DeepEqual(t, http.StatusOK, resp1.StatusCode())
using `"github.com/cloudwego/hertz/pkg/protocol/consts"` instead of `http`

2023-03-23 11:29 UTC, Claude-Zq commented on generator.go
> +		if tk, err := newTokenFromClaims(stdClaims, customClaims, footer); err != nil {
fix

2023-03-23 11:29 UTC, Claude-Zq commented on go.mod
> +	github.com/cloudwego/hertz v0.5.2
fixed

2023-03-23 11:29 UTC, Claude-Zq commented on parser.go
> +func NewV4PublicParseFunc(asymmetricPubKey string, implicit []byte, options ...ParseOption) (ParseFunc, error) {
fixed

2023-03-23 11:29 UTC, Claude-Zq commented on README.md
> +
fixed

2023-03-23 11:29 UTC, Claude-Zq commented on paseto_test.go
> +	assert.DeepEqual(t, http.StatusOK, resp1.StatusCode())
fixed

2023-03-23 11:41 UTC, L2ncE approved these changes
LGTM

2023-03-24 11:05 UTC, Claude-Zq commented
PATL @li-jin-gou @zstone12

2023-03-27 03:03 UTC, li-jin-gou approved these changes

2023-03-27 03:04 UTC, li-jin-gou commented
LGTM

2023-03-27 03:04 UTC, merged